export default [
  {
    Gender: "Male",
    dateOfBbirth: "01/01/2019",
    email: "shaheershaikh79@gmail.com",
    firstName: "shaheer",
    id: undefined,
    ipAddress: "192.169.0.1",
    lastName: "shaikh",
    status: "male",
    subject: "English",
    type: "0",
  },
  {
    Gender: "female",
    dateOfBbirth: "01/01/2019",
    email: "fatimeshaikh79@gmail.com",
    firstName: "fatime",
    id: undefined,
    ipAddress: "192.169.0.1",
    lastName: "shaikh",
    status: "male",
    subject: "English",
    type: "1",
  },
];
